### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by gregorjerse** [polz113/bober#19]
Current landing page is a disaster. I recommend the following implementation:

- the landing page should contain jumbotron and tree links: one for competitors, one for teachers and one for guests.  How about something like  https://www.dropbox.com/ ? Only the Sign up part of the page would be replaced by the links. Maybe even login page (enter code, username/password) and guest link if we can differentiate between teacher and user based on a code they enter.
- the teacher code/link would take teacher to the login page and then to the list of all competitions he has access to.
- the competitor code/link would take competitor directly to the currently running competition (if there is one) or to the list of all currently ongoing competitions.

Would that be OK?

**Comment by janezd** [comment]
Gregor, great!

I like the idea, but I'd move links to competition to the front page. The large majority of users are competitors, not teachers.

I would have a link "Login for teachers" somewhere (not too hidden) at the top, and then the entry for competitors at the center. This link would be present always, in either of the two scenarios below.

At each moment, we either have a competition runnning, or we instead offer past competitions. The easiest way to manage this would, I suppose, be to have essentially two landing pages.

- When the competition is running, the page shows the fields for entering the name and the code, and a button to enter the competition. There are never (and let us not plan for never) two competitions at the same time.

- In the peacetime, we offer past competitions, which don't require any passwords/codes, so we can just publish links. These, however, have to be curated and shouldn't include tests etc. Ideally, they could be organized by age groups (say three groups) and then by years.

With respect to the database, every competition in the system would have a flag denoting whether this is a running competition, a "free" competition or not. If there exists a running competition, we show the competition landing page, otherwise a list of free ones.

**Comment by gregorjerse** [comment]
I think the idea about having two landing pages is great. How about this implementation:
- left side of the landing page is always jumbotron (think about some nice image)
- on the right hand side we have links Teacher, Competitor, Guest. 
- when there is only one ongoing competition, the link Competitor is replaced by the login form for competitors. Links for teachers and guests stay where they are. 

So the landing page looks similar all the time and competitors do not have to waste a single click to login to ongoing competition.

**Comment by janezd** [comment]
We will never have three roles at the same time. We don't accept guests during competition (to avoid confusion - you can bet dozens of competitors will click "guest"), and we don't have competitors when there is no competition.

We will never have multiple competitions at the same time (on the same system).

Hence,
- we either have a competition, where we have a login form and a link for the teacher,
- otherwise, we have a link for the teacher and ... ok, there can be a link for guests or a list of links to competitions.

**Comment by gregorjerse** [comment]
I disagree. How about teachers creating their own competitions? 
Anyway: be both agree on this:
- there is one landing page
- if there is ongoing competition, there is a highlighted form to login as competitor and link to log in as guest.

I will try to find some time to implement it during next week.

**Comment by janezd** [comment]
> How about teachers creating their own competitions?

Doubtfully. :)

> if there is ongoing competition, there is a highlighted form to login as competitor and link to log in as guest.

I don't see much benefit, and on the other hand we'd be just asking for troubles. You can do it, but I predict we're going to have to hide the guest login after too many children go there instead of to the competition. What I learned at this competition is that if there is a link, somebody will click it. :)

But you can implement this and we'll see what happens when we use it.
